[alias]
xtask = "run -p xtask --"
clean-target = "run -p xtask -- clean-target"
clean-target-hard = "run -p xtask -- clean-target-hard"
build-release = "run -p xtask -- build-release"
validate-wgsl = "run -p xtask_wgsl --"
generate-sprite-ktx = "run -p xtask -- generate-sprite-ktx"
check-sprite-ktx = "run -p xtask -- check-sprite-ktx"
